version: '3'
services:

  backend:
    image: good-threads-backend
    restart: always
    # container_name: app_main
    # command: sh -c "yarn install && yarn start"
    # working_dir: /app
    ports:
      - 8080:3000
    volumes:
      - ./.env:/app/.env:ro

  mongo:
    image: mongo:4.4.26
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./.data/mongo:/data/db
      - ./mongo-init-script.js:/docker-entrypoint-initdb.d/mongo-init-script.js:ro

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example  
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/