version: '3'
services:

  backend:
    image: good-threads-backend
    restart: always
    # container_name: app_main
    # command: sh -c "yarn install && yarn start"
    # working_dir: /app
    ports:
      - 8000:3000
    volumes:
      - ./.env:/app/.env:ro

  mongo:
    image: mongo:4.4.26
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./.data/mongo:/data/db:rw
      - ./mongo-init-script.js:/docker-entrypoint-initdb.d/mongo-init-script.js:ro

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9001:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example  
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  prometheus:
    image: prom/prometheus
    ports:
      - 9002:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./.data/prometheus:/prometheus:rw

  grafana:
    image: grafana/grafana
    ports:
      - 9003:3000
    environment:
      GF_SECURITY_ADMIN_USER: root
      GF_SECURITY_ADMIN_PASSWORD: example
    volumes:
      - ./grafana.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:ro
      - ./.data/grafana:/var/lib/grafana:rw